# Generated by Django 4.0 on 2022-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Karachi', 'Karachi'), ('Quetta', 'Quetta'), ('Islamabad', 'Islamabad'), ('Faisalabad', 'Faisalabad')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, null=True, upload_to='doc')),
            ],
        ),
    ]
